
name: Build

on:
  push:
  
    branches: ['main']
    
    # see: https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#example-including-paths
    paths:
      - 'src/**'
      - './build.js'
      
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [26.x]

    steps:
    
    - uses: actions/checkout@v6
        
    - name: Build
      run: |
          npm install
          npm run build
    
    # push changes to GitHub
    - uses: stefanzweifel/git-auto-commit-action@v7
      with:
        commit_message: 'Build'
